# Module Rule Configuration for PostgreSQL
# Project: fresh-todo-app-project-clean
# Environment: dev
# Resource Type: postgres

apiVersion: v1
kind: ModuleRule
metadata:
  project_id: fresh-todo-app-project-clean
  resource_type: postgres
  resource_class: default
  policy: cost-optimization-2024

# ORIGINAL: Overprovisioned Configuration  
module_id: fresh-postgres-overprovisioned
cost_profile: high
instance_class: db.t3.small
storage: 100GB gp3
features: performance_insights_enabled

